openapi: 3.1.0

info:
  title: Entity
  version: 2.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths: {}

components:
  schemas:
    Entity:
      externalDocs:
        url: https://datamodel.tmforum.org/en/latest/Common/Entity
      type: object
      description: Base entity schema for use in TMForum Open-APIs
      allOf:
        - $ref: './Extensible.openapi.yaml#/components/schemas/Extensible'
        - $ref: './Addressable.openapi.yaml#/components/schemas/Addressable'
      properties:
        id:
          readOnly: true
        href:
          readOnly: true
